// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParcelRoutingSystem.Infrastructure.Persistence;

#nullable disable

namespace ParcelRoutingSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ParcelRoutingDbContext))]
    [Migration("20260729050313_AddOperationsHistoryIndexes")]
    partial class AddOperationsHistoryIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EventType", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SubjectType", "SubjectId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.BatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletedRows")
                        .HasColumnType("integer")
                        .HasColumnName("completed_rows");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("FailedRows")
                        .HasColumnType("integer")
                        .HasColumnName("failed_rows");

                    b.Property<string>("FallbackDestinationCountry")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("destination_country")
                        .IsFixedLength();

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_fingerprint")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("parcel_batches", (string)null);
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.BatchRowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_token");

                    b.Property<string>("CountrySource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("country_source");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<decimal>("DeclaredValueEuros")
                        .HasPrecision(29, 12)
                        .HasColumnType("numeric(29,12)")
                        .HasColumnName("declared_value_euros");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("destination_country")
                        .IsFixedLength();

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("WeightKilograms")
                        .HasPrecision(29, 12)
                        .HasColumnType("numeric(29,12)")
                        .HasColumnName("weight_kilograms");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "RowNumber")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAtUtc");

                    b.ToTable("parcel_batch_rows", (string)null);
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.InsuranceApprovalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("insurance_approvals", (string)null);
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.InsuranceRuleEntity", b =>
                {
                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rule_set_version");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_id");

                    b.Property<decimal>("ThresholdExclusiveEuros")
                        .HasPrecision(29, 12)
                        .HasColumnType("numeric(29,12)")
                        .HasColumnName("threshold_exclusive_euros");

                    b.HasKey("RuleSetVersion");

                    b.ToTable("routing_insurance_rules", (string)null);

                    b.HasData(
                        new
                        {
                            RuleSetVersion = 1,
                            Priority = 1000,
                            RuleId = "VALUE-INSURANCE-OVER-1000-EUR",
                            ThresholdExclusiveEuros = 1000m
                        });
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.RoutingDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("approval_state");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid?>("BatchRowId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_row_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<decimal>("DeclaredValueEuros")
                        .HasPrecision(29, 12)
                        .HasColumnType("numeric(29,12)")
                        .HasColumnName("declared_value_euros");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("destination_country")
                        .IsFixedLength();

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("IntendedDepartment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("intended_department");

                    b.PrimitiveCollection<string[]>("MatchedRuleIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("matched_rule_ids");

                    b.PrimitiveCollection<string[]>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("reasons");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_fingerprint")
                        .IsFixedLength();

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rule_set_version");

                    b.Property<decimal>("WeightKilograms")
                        .HasPrecision(29, 12)
                        .HasColumnType("numeric(29,12)")
                        .HasColumnName("weight_kilograms");

                    b.HasKey("Id");

                    b.HasIndex("BatchRowId")
                        .IsUnique()
                        .HasFilter("batch_row_id IS NOT NULL");

                    b.HasIndex("DecidedAtUtc");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RuleSetVersion");

                    b.HasIndex("ApprovalState", "DecidedAtUtc");

                    b.ToTable("routing_decisions", (string)null);
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.RuleSetEntity", b =>
                {
                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Version"));

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Version");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("status = 'Active'");

                    b.ToTable("routing_rule_sets", (string)null);

                    b.HasData(
                        new
                        {
                            Version = 1,
                            ActivatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.WeightBandRuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("department");

                    b.Property<decimal>("LowerBoundExclusive")
                        .HasPrecision(29, 12)
                        .HasColumnType("numeric(29,12)")
                        .HasColumnName("lower_bound_exclusive");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_id");

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rule_set_version");

                    b.Property<decimal?>("UpperBoundInclusive")
                        .HasPrecision(29, 12)
                        .HasColumnType("numeric(29,12)")
                        .HasColumnName("upper_bound_inclusive");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetVersion", "Priority")
                        .IsUnique();

                    b.HasIndex("RuleSetVersion", "RuleId")
                        .IsUnique();

                    b.ToTable("routing_weight_band_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Department = "Mail",
                            LowerBoundExclusive = 0m,
                            Priority = 100,
                            RuleId = "WEIGHT-MAIL-UP-TO-1-KG",
                            RuleSetVersion = 1,
                            UpperBoundInclusive = 1m
                        },
                        new
                        {
                            Id = 2L,
                            Department = "Regular",
                            LowerBoundExclusive = 1m,
                            Priority = 200,
                            RuleId = "WEIGHT-REGULAR-UP-TO-10-KG",
                            RuleSetVersion = 1,
                            UpperBoundInclusive = 10m
                        },
                        new
                        {
                            Id = 3L,
                            Department = "Heavy",
                            LowerBoundExclusive = 10m,
                            Priority = 300,
                            RuleId = "WEIGHT-HEAVY-OVER-10-KG",
                            RuleSetVersion = 1
                        });
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.BatchRowEntity", b =>
                {
                    b.HasOne("ParcelRoutingSystem.Infrastructure.Persistence.BatchEntity", "Batch")
                        .WithMany("Rows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.InsuranceApprovalEntity", b =>
                {
                    b.HasOne("ParcelRoutingSystem.Infrastructure.Persistence.RoutingDecisionEntity", null)
                        .WithOne()
                        .HasForeignKey("ParcelRoutingSystem.Infrastructure.Persistence.InsuranceApprovalEntity", "DecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.InsuranceRuleEntity", b =>
                {
                    b.HasOne("ParcelRoutingSystem.Infrastructure.Persistence.RuleSetEntity", "RuleSet")
                        .WithOne("InsuranceRule")
                        .HasForeignKey("ParcelRoutingSystem.Infrastructure.Persistence.InsuranceRuleEntity", "RuleSetVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.RoutingDecisionEntity", b =>
                {
                    b.HasOne("ParcelRoutingSystem.Infrastructure.Persistence.RuleSetEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleSetVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.WeightBandRuleEntity", b =>
                {
                    b.HasOne("ParcelRoutingSystem.Infrastructure.Persistence.RuleSetEntity", "RuleSet")
                        .WithMany("WeightBands")
                        .HasForeignKey("RuleSetVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.BatchEntity", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("ParcelRoutingSystem.Infrastructure.Persistence.RuleSetEntity", b =>
                {
                    b.Navigation("InsuranceRule");

                    b.Navigation("WeightBands");
                });
#pragma warning restore 612, 618
        }
    }
}
